/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.pkts.java-conventions")
}

dependencies {
    api(project(":pkts-buffers"))
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.mockito:mockito-all:1.8.5")
}

description = "Core Pkts"

