/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.pkts.java-conventions")
    kotlin("jvm") version "1.9.20"
}

dependencies {
    api(project(":pkts-buffers"))
    testImplementation("junit:junit:4.13.1")
    testImplementation("org.mockito:mockito-all:1.8.5")
    implementation(kotlin("stdlib-jdk8"))
}

description = "Core Pkts"

repositories {
    mavenCentral()
}
kotlin {
    jvmToolchain(11)
}
