/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.pkts.java-conventions")
}

dependencies {
    testImplementation("junit:junit:4.13.1")
}

description = "Pkts Buffer Lib"

java {
    withJavadocJar()
}
